pipeline {
    agent { label 'ansible '}

    stages {
        stage('install grafana') {
            steps {
               sh "sudo ansible-playbook /root/promethus.yml"
            }   
        }
    }
}
